---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-binaries:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/* ./package/
    when:
      branch: master
      event: [push,tag]

  docker-publish-master:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/server
    context: package/
    tag: master
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push

  docker-publish:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/server
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag


  slack-notification-failure:
    image: plugins/slack
    channel: engineering
    secrets: [ slack_webhook ]
    when:
      status: failure
      branch: master
      event: [push, tag]

  slack-new-build:
    image: plugins/slack
    channel: engineering
    secrets: [ slack_webhook ]
    when:
      status: success
      branch: master
      event: tag
