---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - push
    - tag

- name: docker-publish-master
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - VERSION=master
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/rancher
    tag: master
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-publish-master-agent
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - VERSION=master
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: rancher/rancher-agent
    tag: master
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-publish
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/rancher
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: docker-publish-agent
  pull: default
  image: plugins/docker
  settings:
    build_args:
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.agent
    password:
      from_secret: docker_password
    repo: rancher/rancher-agent
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github_binary_prerelease
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/rancher-*"
    prerelease: true
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/rancher-*"
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/v2*"
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

- name: chart-publish
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: bin/chart
    target: releases.rancher.com/server-charts
    token:
      from_secret: google_auth_key
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64 

steps:
- name: chart-promote
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper chart/copy
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - promote
    target:
    - promote-stable

- name: chart-publish
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: bin/chart
    target: releases.rancher.com/server-charts
    token:
      from_secret: google_auth_key

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - promote
...
